### ISSUE TITLE
How did you make the SVGs?

### ISSUE THREAD

**Issue by RheingoldRiver** [Ashugeo/set-game#3]
Hello!

I'm learning React and I decided to make a SetGame clone as a learning-React project. Currently, I'm using image files for the icons & [this tool](https://codepen.io/sosuke/pen/Pjoqqp) to convert them to the desired final color, but I stumbled upon your project (I actually searched to see if any finished game existed because I suddenly just wanted very badly to play Set and my images look terrible haha) & saw that you are using SVGs.

So, I was wondering, could you show me how you created your SVGs? I'd rather not copy your paths even if your project is OSS since I'm trying to learn & I'd love to learn how to create SVGs in a situation like this (also you have no license file btw).

Thanks!!
River

**Comment by hugosaintemarie** [comment]
Hi River,

I would to a terrible job at teaching you how to create SVGs, maybe the [MDN guide](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial) would be a good place to start! 🙂 

For reference, the SVGs I use are in  [`index.html:224`](https://github.com/ashugeo/set-game/blob/master/index.html#L224-L237), I just duplicate them as needed to draw cards using the SVG element `<use xlink:href="#id"></use>` (see [`tutorial.js:88`](https://github.com/ashugeo/set-game/blob/693e5cc23b9a12de3931a41cbdff7f99220783b3/js/tutorial.js#L88-L91)).

Happy learning! 😊

**Comment by RheingoldRiver** [comment]
Ok thanks! When you created these, what approach did you take? Did you scan/screenshot an existing card & import into Inkscape and then trace the curves, or build from scratch in Inkscape, or use a font tilde, or some other approach?

**Comment by hugosaintemarie** [comment]
Mmh, that's a good question! I don't really remember.

If I had to do it today I would probably draw the diamond and pill in Inkscape (or any other software). For the tilde, I'd probably use a font and convert it to outlines indeed!
